microsoft/usersim

- inc/usersim/ex.h
- inc/usersim/ke.h
- src/ex.cpp
- src/framework.h
- src/ke.cpp
- src/kernel_um.h
- src/platform.h
- src/platform_user.cpp
- src/ps.cpp
- src/utilities.h
- tests/tests.cpp
> Add some more tests

- inc/usersim/ke.h
- inc/usersim/rtl.h
- src/ke.cpp
- src/platform.h
- tests/tests.cpp
Add KeBugCheck and KeBugCheckEx, which currently throw an exception
Add tests for them that verify the exception thrown
> Add KeBugCheck

- inc/usersim/ex.h
- inc/usersim/ke.h
- src/ex.cpp
- src/ke.cpp
- src/platform.h
- src/platform_user.cpp
- tests/tests.cpp
Add basic tests around allocation and freeing of memory.
Advanced tests (fault injection, etc.) will come later.
> Add basic allocate/free tests

- inc/usersim/ke.h
- src/ke.cpp
- src/platform_user.cpp
- tests/tests.cpp
> Updaet semaphore APIs to close handles on terminate

- README.md
- inc/usersim/ke.h
- src/framework.h
- src/ke.cpp
- src/platform_user.cpp
- tests/tests.cpp
> Add basic DPC api support

- inc/usersim/ke.h
Needed for consistency with wdm.h
> Add KDEFERRED_ROUTINE type definition

- inc/usersim/ke.h
- src/ke.cpp
- src/platform_user.cpp
- tests/tests.cpp
> Expose Ke*Timer apis

- .github/workflows/build.yml
- README.md
- inc/usersim/ke.h
- src/ke.cpp
- src/platform.h
- src/platform_user.cpp
Also various code cleanup
And update the README file to describe leak detection and fault injection
Addresses path of issue #37
> Add leak detection to CI/CD

- src/ke.cpp
- src/rtl.cpp
- tests/tests.cpp
* Fix thread safety issue in threadpool timers
* Fix failure return of RtlULongAdd
> Fix bugs found by ebpf-for-windows tests

- src/ke.cpp
Also add more comments to explain mutex behavior
> Fix threadpool timer synchronization issue

- tests/CMakeLists.txt
- tests/ex_test.cpp
- tests/ke_test.cpp
- tests/mm_test.cpp
- tests/rtl_test.cpp
- tests/tests.vcxproj
- tests/tests.vcxproj.filters
- tests/wdf_test.cpp
No binary impact, only source file reorganization
> Split tests.cpp into a source file per category

- inc/usersim/ex.h
- inc/usersim/ke.h
Only expose CPP functions to C++ callers
Also fix incorrect comment
> Minor C++ header fixes

- inc/usersim/rtl.h
- inc/usersim/se.h
- src/platform_user.cpp
- src/rtl.cpp
- src/se.cpp
- tests/CMakeLists.txt
- tests/se_test.cpp
- tests/tests.vcxproj
- tests/tests.vcxproj.filters
* Add basic RtlValidSid() stub
* Fix RtlLengthSid()
* Initialize SeExports with actual SIDs
* Add test case for SeExports
> Add basic SID support

- inc/usersim/rtl.h
- tests/rtl_test.cpp
> Add RtlUnicodeStringInit

- inc/usersim/ob.h
- src/CMakeLists.txt
- src/ob.cpp
- src/usersim.vcxproj
- src/usersim.vcxproj.filters
- tests/CMakeLists.txt
- tests/ob_test.cpp
- tests/tests.vcxproj
- tests/tests.vcxproj.filters
These are all used by ebpf-for-windows.
Fixes #68
> Add various Ob* APIs

- inc/usersim/se.h
- src/se.cpp
- tests/se_test.cpp
> Add Se* APIs needed by ebpf-for-windows

- src/zw.cpp
Convert byte size to WCHAR length
> Fix bug found by address sanitizer

- cxplat/cxplat_test/cxplat_test.vcxproj
- cxplat/cxplat_test/cxplat_workitem_test.cpp
- cxplat/inc/cxplat_workitem.h
- cxplat/src/cxplat_winkernel/workitem_winkernel.c
- cxplat/src/cxplat_winuser/workitem_winuser.cpp
- src/io.cpp
- tests/io_test.cpp
- tests/tests.vcxproj
- tests/tests.vcxproj.filters
And implement fixes needed for the tests to pass
> Add tests for Io work item APIs

- cxplat/cxplat_test/cxplat_initialization_test.cpp
- cxplat/cxplat_test/cxplat_test.vcxproj
- cxplat/cxplat_test/cxplat_test.vcxproj.filters
- cxplat/src/cxplat_winkernel/cxplat_winkernel.c
- cxplat/src/cxplat_winuser/cxplat_winuser.cpp
> Allow calling cxplat_initialize multiple times

- cxplat/cxplat_test/CMakeLists.txt
- cxplat/cxplat_test/cxplat_fault_injection_test.cpp
- cxplat/src/cxplat_winuser/fault_injection.cpp
Make calls to cxplat_fault_injection_add_module be ref-counted.
> Ref-count add_module_under_test/remove_module_under_test

- cxplat/inc/cxplat_memory.h
- cxplat/src/cxplat_winkernel/memory_winkernel.c
Fixes #122
It will come back when #111 is done, when it will have tests, and winuser implementation.  But temporarily clean up dead code until then.
> Remove cxplat_free_cache_aligned

- cxplat/src/cxplat_winkernel/memory_winkernel.c
When switching back from ExAllocatePool2, didn't the zero-initialization logic back in.
> Fix zero initialization bug

- inc/usersim/wdf.h
- src/wdf.cpp
- tests/wdf_test.cpp
- usersim_dll_skeleton/CMakeLists.txt
- usersim_dll_skeleton/dll_skeleton.cpp
- usersim_dll_skeleton/usersim_dll_skeleton.vcxproj
- usersim_dll_skeleton/usersim_dll_skeleton.vcxproj.filters
> Support multiple devices per usersim driver 

- cxplat/inc/cxplat_memory.h
- cxplat/inc/cxplat_workitem.h
- cxplat/inc/winuser/cxplat_winuser.h
- cxplat/src/cxplat_winkernel/workitem_winkernel.c
- cxplat/src/cxplat_winuser/leak_detector.cpp
- cxplat/src/cxplat_winuser/leak_detector.h
- cxplat/src/cxplat_winuser/workitem_winuser.cpp
- src/fwp_um.cpp
- src/fwp_um.h
- src/nmr_impl.cpp
- src/nmr_impl.h
- src/nmr_um.cpp
- src/platform.h
- src/platform_user.cpp
Use consistent convention suggested by Nick
> Use struct foo_t instead of struct _foo

- cxplat/cxplat_test/CMakeLists.txt
- cxplat/cxplat_test/cxplat_processor_test.cpp
- cxplat/cxplat_test/cxplat_test.vcxproj
- cxplat/cxplat_test/cxplat_test.vcxproj.filters
- cxplat/inc/cxplat.h
- cxplat/inc/cxplat_processor.h
- cxplat/src/cxplat_winkernel/CMakeLists.txt
- cxplat/src/cxplat_winkernel/cxplat_winkernel.vcxproj
- cxplat/src/cxplat_winkernel/cxplat_winkernel.vcxproj.filters
- cxplat/src/cxplat_winkernel/processor_winkernel.c
- cxplat/src/cxplat_winuser/CMakeLists.txt
- cxplat/src/cxplat_winuser/cxplat_winuser.cpp
- cxplat/src/cxplat_winuser/cxplat_winuser.vcxproj
- cxplat/src/cxplat_winuser/cxplat_winuser.vcxproj.filters
- cxplat/src/cxplat_winuser/processor_winuser.cpp
- cxplat/src/cxplat_winuser/winuser_internal.h
- cxplat/src/tags.h
Based on MSQUIC implementations
Fixes #137
Fixes #138
> Add processor APIs to cxplat library

- Directory.Build.props
As per SDL guidelines, I am enabling control flow guard (CFG) in this repo.
> Enable CFG in usersim
