inc/TraceLoggingProvider.h
src/platform_user.cpp
src/usersim.vcxproj
src/usersim.vcxproj.filters

Rather than exposing a custom printk method, instead mock the standard tracelogging API.
Currently this exposes custom APIs to control the tracelogging output.

Mock TraceLogging

---

inc/usersim/ke.h
src/ke.cpp
src/platform_user.cpp
tests/tests.cpp

* Allow `KeFlushQueuedDpcs()` to be called multiple times
* Allow `KeCancelTimer()` to be called at dispatch level
* Run leak detection after, not before, freeing usersim platform state
* Handle race conditions with `KeInsertQueueDpc()`
* Add tests for the above

Bug fixes found by ebpf-for-windows tests

---

inc/usersim/ke.h

DPCs already did, but using KeRaiseIrql with DISPATCH_LEVEL incorrectly used THREAD_PRIORITY_HIGHEST
Fixes #42

Make DISPATCH_LEVEL code run at THREAD_PRIORITY_TIME_CRITICAL

---

src/CMakeLists.txt
tests/CMakeLists.txt

The Source.def file was missing and the NMR tests (which require the Source.def file to work) weren't running

Fix cmake build

---

src/ke.cpp

Thanks to Alan for helping track down what was going on.  Upon process termination, all threads are killed before DllMain is called.  But the DPC design uses persistent threads that each have their own mutex.  If a thread is killed while holding the mutex, this would result in the mutex destructor hitting an assert.  Among other effects, this hung the build because that happens when running export_program_info.exe and bpf2c.exe.
Add a workaround for this issue.

Fix thread mutex destructor assert

---

inc/usersim/ke.h
src/ke.cpp
src/platform_user.cpp
tests/ke_test.cpp

Ensure the following:
1. Dispatch level code cannot migrate across processors.
2. Dispatch level code cannot be preempted by code running at lower IRQLs on the same processor.
3. Dispatch level code cannot preempt other dispatch level code on the same processor.
This requires the following:
1. Emulate kernel thread affinity rather than directly setting and getting the Win32 thread affinity.
2. Set the process to be in the realtime thread priority class. This ensures thread priority orders are strictly honored.
3. Set the Win32 thread affinity to a single processor (within the thread's emulated affinity group) whenever IRQL is raised to dispatch level.
4. Acquire a per-processor mutex whenever IRQL is raised to dispatch level.
A new test case is added and verified.
This PR does not address …

Serialize dispatch level code on each processor

---

src/platform_user.cpp

Since Application Verifier doesn't like it if we try to clean up a thread in DllMain.

Disable fault injection within DllMain

---

src/ke.cpp

Resolves: #60 
The APIs std::condition_variable::notify_all and std::condition_variable::wait require conditions on which the wait is being performed are only modified while holding the lock that wait acquires and releases as part of it's conditional wait. 
Failure to do this can result in missed wake notifications, which shows up as an infinite hang during fault injection tests, with the following stack:
```
00 000000e1`ae16e618 00007ff9`178dd77e     ntdll!ZwWaitForSingleObject+0x14
01 000000e1`ae16e620 00007ff8`efb92e5f     KERNELBASE!WaitForSingleObjectEx+0x8e
02 000000e1`ae16e6c0 00007ff6`cce490e7     msvcp140!Thrd_join+0x1f
03 000000e1`ae16e6f0 00007ff6`ccf5d73f     unit_tests!std::thread::join+0x47 [C:\Program Files\Microsoft Visual …
```

Fix race that causes missed wake

---

inc/usersim/rtl.h
src/rtl.cpp
tests/rtl_test.cpp

Add support for RtlAssert.
Initial implementation is a simple wrapper around KeBugCheckEx.

Add RtlAssert()

---

inc/usersim/ex.h
inc/usersim/ke.h
inc/usersim/mm.h
src/ex.cpp
src/ke.cpp
src/mm.cpp
tests/ex_test.cpp
tests/mm_test.cpp

Add support for the following kernel APIs:
* ExRaiseAccessViolation
* ExRaiseDatatypeMisalignment
* ProbeForRead
* ProbeForWrite (note that MSDN says this is deprecated and code should just use ProbeForRead instead, hence the implementation, but ebpf-for-windows uses ProbeForWrite)

Add probe APIs and tests

---

inc/TraceLoggingProvider.h
inc/usersim/etw.h
inc/usersim/ke.h
src/CMakeLists.txt
src/etw.cpp
src/ke.cpp
src/platform_user.cpp
src/usersim.vcxproj
src/usersim.vcxproj.filters
tests/CMakeLists.txt
tests/etw_test.cpp
tests/ke_test.cpp
tests/mm_test.cpp
tests/tests.vcxproj
tests/tests.vcxproj.filters

* Add support for `KfRaiseIrql()`, including tests.  The DDK just defines `KeRaiseIrql()` as an inline wrapper around `KfRaiseIrql()` so we need to expose `KfRaiseIrql()` when linking.
* Add support for `EtwRegister()` and `EtwUnregister()`, including tests.
* Add empty stubs for `EtwWriteTransfer()` and `EtwSetInformation()`.
* Remove unused function `test_probe_for_read_exception_filter()`.
Addresses parts of #69 #70

Add KfRaiseIrql and some Etw APIs

---

README.md
inc/usersim/io.h
inc/usersim/rtl.h
inc/usersim/wdf.h
inc/usersim/zw.h
src/CMakeLists.txt
src/usersim.vcxproj
src/usersim.vcxproj.filters
src/wdf.cpp
src/zw.cpp
tests/tests.vcxproj
tests/tests.vcxproj.filters
tests/wdf_test.cpp
tests/zw_test.cpp
usersim_dll_skeleton/dll_skeleton.c

Override calls to HKLM to use HKCU for now. This is because kernel code has write access to HKLM, so to accurately simulate such calls from a normal test app, we redirect them to HKCU if HKLM access fails.
Also add a couple more Wdf functions needed by ebpf-for-windows

Add Zw registry overrides

---

inc/usersim/ke.h
src/ke.cpp
tests/ke_test.cpp

Note:
This implementation permits using KEVENT as a local stack variable without leaking large numbers of Win32 handles. 
It is a prerequisite to fixing https://github.com/microsoft/ebpf-for-windows/issues/2787.

Implement kevent

---

cxplat/src/cxplat_winuser/leak_detector.cpp
cxplat/src/cxplat_winuser/leak_detector.h
cxplat/src/cxplat_winuser/memory_winuser.cpp

When a double-free is detected, show the original allocation stack, and the stack of the original free.
Not yet ready for review, needs cleanup and simplification first.

Diagnose double frees

---

cxplat/cxplat_test/cxplat_workitem_test.cpp
cxplat/inc/cxplat_workitem.h
cxplat/src/cxplat_winkernel/workitem_winkernel.c
cxplat/src/cxplat_winuser/workitem_winuser.cpp
src/io.cpp

Previously, if the caller wanted to free the work item within the work item routine, the caller had to store the work item pointer
in some context structure passed to the routine, but the cxplat code that calls the callback already has the work item pointer.
This PR changes the callback prototype to include the work item as an argument so the caller need not jump through that hoop.
Passing it as an argument is consistent with https://learn.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms687396(v=vs.85)
Fixes #104

Add work item as an argument to the work_item_routine

---

cxplat/inc/cxplat_common.h
cxplat/inc/winkernel/cxplat_winkernel.h
cxplat/inc/winuser/cxplat_winuser.h
cxplat/src/cxplat_winkernel/cxplat_winkernel.c

Instead of assuming that assert() exists on every platform, make it platform specific.

Use NT_ASSERT in winkernel

---

cxplat/src/cxplat_winkernel/memory_winkernel.c

ExAllocatePoolWithTag does not zero-initialize memory

Fix memory initialization bug in cxplat winkernel

---

cxplat/cxplat_test/cxplat_memory_test.cpp
cxplat/inc/cxplat_memory.h
cxplat/src/cxplat_winkernel/cxplat_winkernel.vcxproj
cxplat/src/cxplat_winkernel/memory_winkernel.c
cxplat/src/cxplat_winkernel/workitem_winkernel.c
cxplat/src/cxplat_winuser/cxplat_winuser.vcxproj
cxplat/src/cxplat_winuser/cxplat_winuser.vcxproj.filters
cxplat/src/cxplat_winuser/memory_winuser.cpp
cxplat/src/cxplat_winuser/winuser_internal.h
cxplat/src/cxplat_winuser/workitem_winuser.cpp
cxplat/src/memory.c
cxplat/src/tags.h
inc/usersim/ex.h
src/etw.cpp
src/ex.cpp
src/fwp_um.cpp
src/io.cpp
src/platform.h
src/platform_user.cpp
src/se.cpp
src/tags.h
src/usersim.vcxproj
src/usersim.vcxproj.filters
src/wdf.cpp

* Remove non-tag-based allocation APIs
* Add `cxplat_free_any_tag()` which is required by some callers
* Rename `cxplat_utf8_string_free()` to `cxplat_free_utf8_string()` for consistency with other APIs
* Add `cxplat_free_string()` to match `cxplat_duplicate_string()`
Any whitespace changes come from the format-code utility.
Fixes #97

Remove non-tag-based allocation APIs

---

cxplat/cxplat_test/cxplat_fault_injection.cpp
cxplat/cxplat_test/cxplat_fault_injection_test.cpp
cxplat/cxplat_test/cxplat_test.vcxproj
cxplat/cxplat_test/cxplat_test.vcxproj.filters
cxplat/inc/winuser/cxplat_fault_injection.h
cxplat/src/cxplat_winuser/cxplat_winuser.cpp
cxplat/src/cxplat_winuser/fault_injection.cpp

Resolves: #107
Fault injection was originally designed as a static lib. It would then inject faults in code in the current process.
Now that it is being used as a DLL, it inject faults in the module that calls cxplat_fault_injection_initialize.

Restrict fault injection to requested modules 

---

cxplat/src/cxplat_winkernel/memory_winkernel.c

Per https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exallocatepool2, ExAllocatePool2 is fairly new and isn't available downlevel.

Don't use ExAllocatePool2 as it doesn't exist downlevel

---

src/ke.cpp
src/platform.h

Previously we redefined them as thread priorities, but this caused problems with driver code that compiles with the real headers (i.e., using the real values), including test failures in ebpf-for-windows tests.
In this PR, we deal with the mapping internally to usersim.dll and let the caller use real values like DISPATCH_LEVEL = 2.

Use actual IRQL values

---

src/ke.cpp

Running the DPC from the timer thread give incorrect behavior. The DPC should run on the CPU specified in the DPC.
Resolves: #132

Queue DPC on timer expiry

---

Directory.Build.props

Resolve: #151 
Add check if parent folder contains a Directory.Build.props file and import it if present.

Import Directory.Build.props from parent if present

---

inc/usersim/ke.h
src/ke.cpp
src/platform_user.cpp
tests/ke_test.cpp

Add mocks for:
KeGetProcessorNumberFromIndex
KeGetProcessorIndexFromNumber
KeSetTargetProcessorDpcEx
Assumes group == 64 processors.

Add APIs to handle PROCESSOR_NUMBER

---

inc/usersim/ke.h
src/ke.cpp

KeSetTargetProcessorDpcEx should return NTSTATUS not void.

Fix signature of KeSetTargetProcessorDpcEx

---

inc/usersim/rtl.h
tests/rtl_test.cpp

Add UTF8_STRING support, including converting to and from UNICODE_STRING.

Add UTF8_STRING support

---

inc/usersim/rtl.h
tests/rtl_test.cpp

The Rtl*Avl functions are already exposed in ntdll. This change adds them to usersim headers, along with testing of each API.
This change closes #177

Add support for RTL_AVL_TABLE and associated functions

---

inc/usersim/rtl.h

PR #178 added support for the RTL_AVL_TABLE but was missing a forward declaration of the struct required for compiling. This change addresses that by adding the necessary declaration.

Add missing forward declaration for RTL_AVL_TABLE

---

inc/usersim/ex.h
src/ex.cpp
tests/ex_test.cpp

This pull request primarily introduces a new type `EX_RUNDOWN_REF_CACHE_AWARE`, which is an extension of `EX_RUNDOWN_REF` and is designed to be cache aware for better performance. It also adds new APIs to allocate, acquire, release, and free this new type. Additionally, it includes tests for these new APIs and the existing `EX_RUNDOWN_REF` APIs.
Here are the most important changes:
**Type and API additions:**
* [`inc/usersim/ex.h`](diffhunk://#diff-18945575e3a48a3cd91cdbb2c192cfd97519c083f41e146594d5ed9ff8a2ea80R39-R44): Introduced a new type `EX_RUNDOWN_REF_CACHE_AWARE` which is similar to `EX_RUNDOWN_REF` but is cache aware. This type is expected to improve performance by being aware of the cache. Also, added new APIs `ExAllocateCacheAwareRundownProtection`, …

Simulate EX_RUNDOWN_REF_CACHE_AWARE APIS

---

src/ke.cpp

This pull request includes a change to the `KeSetSystemAffinityThreadEx(KAFFINITY affinity)` function in the `src/ke.cpp` file. The change modifies the error handling mechanism. Instead of triggering a bug check when an error occurs, the function now returns 0.
In detail:
* [`src/ke.cpp`](diffhunk://#diff-6bf312c06fbab586948463c7433568611f84ae80d29800727d16a4eaa227685bL231-R231): Modified the `KeSetSystemAffinityThreadEx(KAFFINITY affinity)` function to return 0 instead of triggering a bug check when `SetThreadAffinityMask(GetCurrentThread(), affinity)` returns an error.

KeSetSystemGroupAffinityThread does not match kernel behavior

---

inc/usersim/ke.h
src/ke.cpp
tests/ke_test.cpp

The cost of emulating KeRaiseIrql and KeLowerIrql significantly distort performance tests when running against usersim.
For the use case where performance tests are being run, it is useful to override the behavior of KeRaiseIrql and KeLowerIrql by pinning the CPU to a processor and raising the thread priority.

Permit caller opt-in to improve raise/lower irql perf

---

inc/usersim/ps.h

I misunderstood how the SAL needed to match the DDK on the API I just introduced with #191 
This fixes the SAL to match the DDK.

Fix SAL on PsGetProcessExitStatus

---

inc/usersim/ps.h
src/ps.cpp
tests/ps_test.cpp

Adding two more `Ps*` APIs - for getting a process's create and exit times, and corresponding tests.

Add PsGetProcessCreateTimeQuadPart and PsGetProcessExitTime

---

inc/TraceLoggingProvider.h

This PR contains
-  _tlgBinary type for TraceLoggingBinary tracing support to log binary data.
Test log in ebpf-for-windows, where the key in the map is logged as is:
```
[0]0004.1B4C::2024/08/17-14:00:48.586549200 [EbpfForWindowsProvider]{"Message":"
Map lookup","Type":"hash","name":"
xxxx","(key).Length":12,"(key)":"0x0A0101031389000011000000","meta":{"provider":"EbpfForWindowsProvider","event":"EbpfGenericMessage","time":"2024-08-17T21:00:48.5865492Z","cpu":0,"pid":4,"tid":6988,"channel":11,"level":4,"keywords":"0x40"}}
```
Note: map name is masked with xxxx.
Please see the draft PR https://github.com/microsoft/ebpf-for-windows/pull/3781

Add TraceLoggingBinary in TraceLoggingProvider

---

src/fwp_um.cpp

Currently the usersim implementation of WFP only expects ACTION_PERMIT for auth_connect and connect_redirect layers. Ideally it should allow `ACTION_CONTINUE` also.

Update WFP mock to allow `ACTION_CONTINUE`

---

inc/usersim/ke.h
src/ke.cpp

This PR adds a mock implementation of `KeExpandKernelStackAndCalloutEx()` API.

Add mock for `KeExpandKernelStackAndCalloutEx`

---

inc/usersim/ke.h
src/ke.cpp

This pull request introduces a new function `KfLowerIrql` to the `USERSIM_API` and implements it to call the existing `KeLowerIrql` function. This change enhances the API by providing an additional method to lower the IRQL.
* [`inc/usersim/ke.h`](diffhunk://#diff-b8dcb37bfb713c012fcd5f680d7c8d09631115092cca187a2bb90707b9c8154eR79-R82): Added the declaration of the `KfLowerIrql` function.
* [`src/ke.cpp`](diffhunk://#diff-6bf312c06fbab586948463c7433568611f84ae80d29800727d16a4eaa227685bR199-R203): Implemented the `KfLowerIrql` function to call `KeLowerIrql`.

Add KfLowerIrql shim

---

.github/workflows/build.yml

This pull request includes a change to the GitHub Actions workflow configuration to support multiple architectures.
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L100-R100): Modified the `BUILD_PLATFORM` to use `${{matrix.architecture}}` instead of hardcoding `x64`.

Set cmake arch based on matrix

---

src/Source.def
src/fwp_um.cpp
src/fwp_um.h

Add additional WFP APIs - 
FwpmDeleteProviderByKey0
FwpmDeleteCalloutByKey0
FwpmDeleteSubLayerByKey0

Add WFP provider, callout, sublayer delete APIs

---

inc/usersim/ke.h
src/ke.cpp
tests/ke_test.cpp

This pull request introduces new functions to manage group affinity for threads, updates the kernel code to implement these functions, and adds corresponding tests to ensure their correctness. The most important changes include the addition of new API functions, their implementation, and the creation of test cases.
* [`inc/usersim/ke.h`](diffhunk://#diff-b8dcb37bfb713c012fcd5f680d7c8d09631115092cca187a2bb90707b9c8154eR155-R165): Added `KeSetSystemGroupAffinityThread` and `KeRevertToUserGroupAffinityThread` to manage group affinity for threads.
* [`src/ke.cpp`](diffhunk://#diff-6bf312c06fbab586948463c7433568611f84ae80d29800727d16a4eaa227685bR308-R325): Implemented `KeSetSystemGroupAffinityThread` and `KeRevertToUserGroupAffinityThread` to set and revert group affinity for the current …

Add group affinity stubs

---

inc/usersim/ke.h
src/ke.cpp

This pull request includes changes to the `USERSIM_API` to add new functions and improve error handling in `ke.cpp`. The most important changes include adding new API functions for querying processor counts and refining error handling in the `KeSetSystemGroupAffinityThread` function.
* Added `KeQueryActiveProcessorCount` and `KeQueryActiveProcessorCountEx` functions to `inc/usersim/ke.h` to provide API access for querying active processor counts.
* Implemented `KeQueryActiveProcessorCount` and `KeQueryActiveProcessorCountEx` functions in `src/ke.cpp` to call the corresponding maximum processor count functions.
* Improved error handling in the `KeSetSystemGroupAffinityThread` function by conditionally using `UNREFERENCED_PARAMETER` for the `error` variable in non-debug builds, and …

Fix build breaks when linking with usersim againt code built against cxplat_kernel

---

src/ke.cpp

Associate timers with a thread pool environment and a thread pool with minimum of 1 thread. This allows timers to expire during DllMain's process detach when the loader lock is held.

Reserve thread

---

src/ke.cpp

This pull request includes several changes to the `src/ke.cpp` file, focusing on improving the handling of the threadpool callback environment by using `std::optional` and making minor formatting adjustments.
* Included the `<optional>` header and changed the `TP_CALLBACK_ENVIRON` variable to use `std::optional` for better management of its initialization state. [[1]](diffhunk://#diff-6bf312c06fbab586948463c7433568611f84ae80d29800727d16a4eaa227685bR10) [[2]](diffhunk://#diff-6bf312c06fbab586948463c7433568611f84ae80d29800727d16a4eaa227685bL33-R34)
* Updated the initialization and cleanup logic for the threadpool callback environment to use `std::optional` methods, ensuring proper resource management. [[1]](diffhunk://#diff-6bf312c06fbab586948463c7433568611f84ae80d29800727d16a4eaa227685bL56- …

Fix fault injection crash

---

cxplat/cxplat_test/cxplat_processor_test.cpp
cxplat/inc/cxplat_processor.h
cxplat/src/cxplat_winkernel/processor_winkernel.c
cxplat/src/cxplat_winuser/processor_winuser.cpp

This pull request introduces a new locking mechanism using spin locks and lock queue handles in the `cxplat` library. The changes include new function definitions, type declarations, and test cases to ensure the functionality is correctly implemented and tested.
* Added new type definitions for `cxplat_spin_lock_t` and `cxplat_lock_queue_handle_t` in `cxplat/inc/cxplat_processor.h` to support the new locking mechanism.
* Implemented new functions for acquiring and releasing in-stack queued spin locks in `cxplat/src/cxplat_winkernel/processor_winkernel.c`. These functions wrap the corresponding kernel functions.
* Added similar functions for acquiring and releasing in-stack queued spin locks in `cxplat/src/cxplat_winuser/processor_winuser.cpp`, using SRW locks for user-mode implementation. …

Add cxplat queued spinlocks

---

cxplat/cxplat_test/cxplat_processor_test.cpp
cxplat/inc/cxplat_processor.h
cxplat/src/cxplat_winkernel/processor_winkernel.c
cxplat/src/cxplat_winuser/processor_winuser.cpp

This pull request includes significant changes to the spin lock implementation and associated tests in the `cxplat` project. The main updates involve renaming and refactoring spin lock types and methods to improve clarity and functionality.
* [`cxplat/inc/cxplat_processor.h`](diffhunk://#diff-b86642399b87981cb1bccf6102b366fba25d68cc0169ea2fa1a72e3d0214db61L33-R48): Renamed `cxplat_spin_lock_t` to `cxplat_queue_spin_lock_t` and added new types and methods for `cxplat_spin_lock_t` and `cxplat_irql_t`. [[1]](diffhunk://#diff-b86642399b87981cb1bccf6102b366fba25d68cc0169ea2fa1a72e3d0214db61L33-R48) [[2]](diffhunk://#diff-b86642399b87981cb1bccf6102b366fba25d68cc0169ea2fa1a72e3d0214db61L53-R84)
* [`cxplat/src/cxplat_winkernel/processor_winkernel.c`](diffhunk://#diff-15fdc4b49da9dbb62788c0abd27d50 …

Add support for vanilla spinlocks

---

cxplat/cxplat_test/CMakeLists.txt
cxplat/cxplat_test/cxplat_test.vcxproj
cxplat/cxplat_test/cxplat_test.vcxproj.filters
cxplat/cxplat_test/cxplat_time_test.cpp
cxplat/inc/cxplat.h
cxplat/inc/cxplat_time.h
cxplat/src/cxplat_winkernel/CMakeLists.txt
cxplat/src/cxplat_winkernel/cxplat_winkernel.vcxproj
cxplat/src/cxplat_winkernel/cxplat_winkernel.vcxproj.filters
cxplat/src/cxplat_winkernel/time_winkernel.c
cxplat/src/cxplat_winuser/CMakeLists.txt
cxplat/src/cxplat_winuser/cxplat_winuser.vcxproj
cxplat/src/cxplat_winuser/cxplat_winuser.vcxproj.filters
cxplat/src/cxplat_winuser/time_winuser.cpp

This pull request introduces a new feature for time querying in the `cxplat` library, including both precise and approximate time queries with options to include or exclude suspended time. The changes span multiple files to integrate this new functionality.
Key changes include:
* [`cxplat/inc/cxplat_time.h`](diffhunk://#diff-5bec8da9c76b3c132ed6bc37947cd14a525665ae4c69857a032e330be0e79363R1-R15): Added declarations for `cxplat_query_time_since_boot_precise` and `cxplat_query_time_since_boot_approximate` functions.
* [`cxplat/src/cxplat_winkernel/time_winkernel.c`](diffhunk://#diff-d3b578af323f173739b86d8302fa0b991474a991c70d9eec696448528d980656R1-R37): Implemented the time query functions for the winkernel platform.
* [`cxplat/src/cxplat_winuser/time_winuser.cpp`](diffhunk://#diff-34bff659 …

Expose timestamp APIs

---

README.md
cxplat/src/cxplat_winuser/CMakeLists.txt
sample/sample.vcxproj
src/usersim.vcxproj

This pull request includes updates to various project files to reference a new Windows SDK version (10.0.26100.0) in addition to the existing version (10.0.22621.0). The changes ensure that the new SDK paths are included in the project configurations.
Updates to include new Windows SDK version:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L20-R20): Updated the `AdditionalIncludeDirectories` to include `$(WindowsSdkDir)Include0.0.26100.0\km` in the setup instructions.
* [`cxplat/src/cxplat_winuser/CMakeLists.txt`](diffhunk://#diff-f045fd64d5ca591a8582c4c3ec5fd9b955131739832f82eabe1548ae69feee35R32): Added `$(WindowsSdkDir)include/10.0.26100.0` to the `target_include_directories` for the `cxplat_winuser` target.
* …

Add support for building against the new WDK 26100

---

CMakeLists.txt
cxplat/cxplat_test/cxplat_test.vcxproj
cxplat/src/cxplat_winkernel/cxplat_winkernel.vcxproj
cxplat/src/cxplat_winkernel/packages.config
cxplat/src/cxplat_winuser/cxplat_winuser.vcxproj
packages.config
sample/sample.vcxproj
setup_build/setup_build.vcxproj
src/framework.h
src/usersim.vcxproj
tests/tests.vcxproj
usersim_dll_skeleton/usersim_dll_skeleton.vcxproj
usersim_dll_skeleton/usersim_dll_skeleton.vcxproj.filters
wdk.props

This pull request includes several updates to the project configuration files to integrate and utilize the Windows Driver Kit (WDK) and the Windows SDK via NuGet packages. The main changes involve modifying the project files to import a new `wdk.props` file, updating the Windows Target Platform Version, and adjusting include directories.
Key changes include:
* **`CMakeLists.txt`:** Added logic to install required NuGet packages for WDK and Windows SDK and set the `WDK_ROOT` based on the platform (arm64 or x64).
* **`wdk.props`:** Added a new file to import the necessary properties and targets from the installed NuGet packages.
* **Project Files:** Updated various project files (`.vcxproj`) to import the `wdk.props` file and set the Windows Target Platform Version to `10.0.26100.0`. This …

Switch to building with WDK nuget

---

src/usersim.vcxproj

This pull request includes a modification to the `src/usersim.vcxproj` file to update the include directories.
Changes in include directories:
* [`src/usersim.vcxproj`](diffhunk://#diff-ef27bb4c938df324692a9a12cd49a8392b5f9b270677cdcec2bed28fe6a1fff7L67-R67): Updated the `AdditionalIncludeDirectories` to use `$(WdkContentRoot)` instead of `$(WindowsSdkDir)` for the `10.0.26100.0\km` directory. This change ensures that the correct directories are referenced for the project.

Fix paths in fuzzerdebug

---

cxplat/src/cxplat_winuser/processor_winuser.cpp

This pull request includes a small change to the `cxplat/src/cxplat_winuser/processor_winuser.cpp` file. The change ensures that the `ReleaseSRWLockExclusive` function is called when releasing a spin lock at the DPC level.
* [`cxplat/src/cxplat_winuser/processor_winuser.cpp`](diffhunk://#diff-5b4e47699538d34f879d62bbf514e5963bfae8994ec48e0fac8938721f218b79R168): Added a call to `ReleaseSRWLockExclusive` in the `cxplat_release_spin_lock_from_dpc_level` function to properly release the spin lock.

Fix cxplat_release_spin_lock_from_dpc_level

---

inc/usersim/ke.h
src/ke.cpp
src/platform.h
tests/ke_test.cpp

This pull request includes several changes to the `usersim` module, focusing on improving thread priority and affinity management. The changes involve replacing existing functions with new ones that cache thread priority and affinity to optimize performance.
* Replaced `usersim_set_affinity_and_priority_override` and `usersim_clear_affinity_and_priority_override` with `usersim_set_current_thread_priority` and `usersim_set_current_thread_affinity` functions to manage thread priority and affinity more efficiently by caching values. [[1]](diffhunk://#diff-b8dcb37bfb713c012fcd5f680d7c8d09631115092cca187a2bb90707b9c8154eL93-R98) [[2]](diffhunk://#diff-6bf312c06fbab586948463c7433568611f84ae80d29800727d16a4eaa227685bR116-R180)
* Introduced new thread-local variables to cache thread priority and …

Add group affinity

---

src/fwp_um.cpp

test_remove_flow_context is used to simulate calls to flowDeleteFn when flow terminates.  flowDeleteFn will only ever be called if associated flow context exists.
Adding check to ensure delete context is called only if the context exists.

Delete flow context only if it exists
